Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,11 +1,3 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
 name: Java CI with Maven
 
 on:
@@ -28,27 +20,47 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml
+      if: always() # Run always even if previous steps failed to get error output
+    - name: Check build status
+      if: steps.Build.outcome != 'success'
+      run: |
+        echo "Maven build failed. Check the logs for details."
+        exit 1
+    - name: Extract Version
+      id: get_version
+      run: |
+        VERSION=$(grep '<version>' pom.xml | sed 's/<version>\(.*\)<\/version>/\1/')
+        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
-        name: setSound
-        path: target/*.jar
+        name: setSound-${{ steps.get_version.outputs.VERSION }}
+        path: target/setSound-${{ steps.get_version.outputs.VERSION }}.jar # Assumes your jar name is setSound-${VERSION}.jar
+
   release:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+      - name: Get Version from Build
+        uses: actions/github-script@v6
+        id: get_version_from_build
+        with:
+          script: |
+            const version = context.payload.repository.default_branch_ref.match(/refs\/heads\/(.*)/)[1]
+            return { version: `${version}` }
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ github.ref }}
+          tag_name: v${{ steps.get_version_from_build.outputs.version }} #Improved Tag Name
+          release_name: Release v${{ steps.get_version_from_build.outputs.version }} # Improved Release Name
           body: |
-            Changes in this Release
+            Release v${{ steps.get_version_from_build.outputs.version }}
+            Changes in this Release:
             - First Change
             - Second Change
           draft: false
